### ISSUE TITLE
Embedding files other than a image

### ISSUE THREAD

**Issue by poxon** [ryanwang520/poi#47]
Hello,

thanks a lot for creating this library! I just wanted to check with you is there any chance of embedding other objects aside from an image into the Excel file (for example a PDF file)? This is something Excel provides through its UI so I was just wondering if this library covers that as well.

Thanks a lot!

**Comment by ryanwang520** [comment]
POI uses [xlsxwriter](https://xlsxwriter.readthedocs.io) under the hood, I don't think xlsxwriter supports embedding a PDF object directly.
